camera_matrix:
  rows: 3
  cols: 3
  data:
  - 273.0159338676917
  - 0.0
  - 324.9600183326164
  - 0.0
  - 273.6241547791448
  - 239.79797983978264
  - 0.0
  - 0.0
  - 1.0
distortion_coefficients:
  rows: 1
  cols: 5
  data:
  - -0.25065305679792266
  - 0.061861452467874695
  - -0.00027867065454988485
  - -0.00012866330962291547
  - -0.006813878971199823
